/*
 * This file is part of the Black Magic Debug project.
 *
 * Copyright (C) 2011  Black Sphere Technologies Ltd.
 * Written by Gareth McMullin <gareth@blacksphere.co.nz>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/* This file implements the platform specific functions for the F4 Discovery implementation. */

#include "platform.h"

#include "ch.h"
#include "exception.h"
#include "general.h"
#include "morse.h"

jmp_buf         fatal_error_jmpbuf;
extern uint32_t _ebss;  // NOLINT(bugprone-reserved-identifier,cert-dcl37-c,cert-dcl51-cpp)

int platform_hwversion(void) { return 0; }

void platform_init(void) {}

void platform_nrst_set_val(bool assert) { (void)assert; }

bool platform_nrst_get_val(void) { return false; }

const char *platform_target_voltage(void) { return NULL; }

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Warray-bounds"

void platform_request_boot(void) {}

#pragma GCC diagnostic pop

#ifdef PLATFORM_HAS_POWER_SWITCH
bool platform_target_get_power(void) {}

bool platform_target_set_power(const bool power) { return true; }
#endif

void platform_target_clk_output_enable(bool enable) { (void)enable; }

bool platform_spi_init(const spi_bus_e bus) {
    (void)bus;
    return false;
}

bool platform_spi_deinit(const spi_bus_e bus) {
    (void)bus;
    return false;
}

bool platform_spi_chip_select(const uint8_t device_select) {
    (void)device_select;
    return false;
}

uint8_t platform_spi_xfer(const spi_bus_e bus, const uint8_t value) {
    (void)bus;
    return value;
}

void platform_delay(uint32_t ms) {
    platform_timeout_s timeout;
    platform_timeout_set(&timeout, ms);
    while (!platform_timeout_is_expired(&timeout)) continue;
}

uint32_t platform_time_ms(void) { return chTimeI2MS(chVTGetSystemTime()); }

/*
 * Assume some USED_SWD_CYCLES per clock and CYCLES_PER_CNT cycles
 * per delay loop count with 2 delay loops per clock
 */

/* Values for STM32F103 at 72 MHz */
#define USED_SWD_CYCLES 22
#define CYCLES_PER_CNT  10

void platform_max_frequency_set(const uint32_t frequency) {
    // #ifdef BITBANG_CALIBRATED_FREQS
    // 	/*
    // 	 * If the frequency requested is above the value given when no delays are used of any kind,
    // 	 * then set the clock divider to UINT32_MAX which the bitbanging routines translate to the right thing.
    // 	 */
    // 	if (frequency > BITBANG_0_DELAY_FREQ)
    // 		target_clk_divider = UINT32_MAX;
    // 	/* If the frequency requested is 0, then set the divider factor to the largest available number */
    // 	else if (!frequency)
    // 		target_clk_divider = UINT32_MAX - 1U;
    // 	else {
    // 		/*
    // 		 * For everything else, start by dividing the CPU frequency by the requested
    // 		 * frequency to make a division ratio for the divider
    // 		 */
    // 		const uint32_t ratio = rcc_ahb_frequency / frequency;
    // 		/* Then apply the offset and division factor to arrive at a divider value */
    // 		target_clk_divider = (ratio - BITBANG_DIVIDER_OFFSET) / BITBANG_DIVIDER_FACTOR;
    // 	}
    // #else
    // 	uint32_t divisor = rcc_ahb_frequency - USED_SWD_CYCLES * frequency;
    // 	/* If we now have an insanely big divisor, the above operation wrapped to a negative signed number. */
    // 	if (divisor >= 0x80000000U) {
    // 		target_clk_divider = UINT32_MAX;
    // 		return;
    // 	}
    // 	divisor /= 2U;
    // 	target_clk_divider = divisor / (CYCLES_PER_CNT * frequency);
    // 	if (target_clk_divider * (CYCLES_PER_CNT * frequency) < divisor)
    // 		++target_clk_divider;
    // #endif
}

uint32_t platform_max_frequency_get(void) {
    // #ifdef BITBANG_CALIBRATED_FREQS
    // 	/* If we aren't applying a division factor, return the no-delay clock frequency */
    // 	if (target_clk_divider == UINT32_MAX)
    // 		return BITBANG_NO_DELAY_FREQ;
    // 	/*
    // 	 * Otherwise we have to run the above calculations in reverse:
    // 	 * Start by multiplying the divider used by the division factor, then add the offset to get back to a ratio.
    // 	 * Finally, divide the CPU clock frequency by the ratio to get back to the actual clock frequency being
    // 	 * generated by the bitbanging routines.
    // 	 */
    // 	const uint32_t ratio = (target_clk_divider * BITBANG_DIVIDER_FACTOR) + BITBANG_DIVIDER_OFFSET;
    // 	return rcc_ahb_frequency / ratio;
    // #else
    // 	uint32_t result = rcc_ahb_frequency;
    // 	result /= USED_SWD_CYCLES + CYCLES_PER_CNT * target_clk_divider;
    // 	return result;
    // #endif
    return 0u;
}
